### ISSUE TITLE
rio-alpha giving a ValueError on an RGBA tif

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-alpha#31]
Using the geotiff here: https://github.com/mapbox/rio-alpha/blob/roll-with-it/tests/fixtures/landsat/LC80460272013104LGN01_l8sr.tif

```
$ rio alpha tests/fixtures/landsat/LC80460272013104LGN01_l8sr.tif /tmp/foo.tif
```

Raises an exception of `ValueError: rollaxis: start (4) must be >=0 and < 4`

<details>
 <summary>Full traceback</summary>
```
Traceback (most recent call last):
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 31, in manualRead
    return work_func(srcs, window, ij, global_args), window
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 66, in _alpha_worker
    g_args['ndv'])
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 32, in calc_alpha
    alpha = mask_exact(rgb, ndv)
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha_mask.py", line 21, in mask_exact
    alpha = np.any(np.rollaxis(img, 0, depth) != ndv, axis=2)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/numpy/core/numeric.py", line 1452, in rollaxis
    raise ValueError(msg % ('start', start, n + 1))
ValueError: rollaxis: start (4) must be >=0 and < 4
Traceback (most recent call last):
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 120, in add_alpha
    rm.run(processes)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 109, in run
    for data, window in self.pool.imap_unordered(reader_worker, self.windows):
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/single_process_pool.py", line 9, in imap_unordered
    yield reader_worker(i)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 34, in manualRead
    raise e
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 31, in manualRead
    return work_func(srcs, window, ij, global_args), window
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 66, in _alpha_worker
    g_args['ndv'])
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 32, in calc_alpha
    alpha = mask_exact(rgb, ndv)
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha_mask.py", line 21, in mask_exact
    alpha = np.any(np.rollaxis(img, 0, depth) != ndv, axis=2)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/numpy/core/numeric.py", line 1452, in rollaxis
    raise ValueError(msg % ('start', start, n + 1))
ValueError: rollaxis: start (4) must be >=0 and < 4
Traceback (most recent call last):
  File "/Users/mperry/env/mapbox35/bin/rio", line 11, in <module>
    load_entry_point('rasterio', 'console_scripts', 'rio')()
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mperry/work/rio-alpha/rio_alpha/scripts/cli.py", line 77, in alpha
    workers)
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 120, in add_alpha
    rm.run(processes)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 109, in run
    for data, window in self.pool.imap_unordered(reader_worker, self.windows):
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/single_process_pool.py", line 9, in imap_unordered
    yield reader_worker(i)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 34, in manualRead
    raise e
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/riomucho/__init__.py", line 31, in manualRead
    return work_func(srcs, window, ij, global_args), window
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 66, in _alpha_worker
    g_args['ndv'])
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha.py", line 32, in calc_alpha
    alpha = mask_exact(rgb, ndv)
  File "/Users/mperry/work/rio-alpha/rio_alpha/alpha_mask.py", line 21, in mask_exact
    alpha = np.any(np.rollaxis(img, 0, depth) != ndv, axis=2)
  File "/Users/mperry/env/mapbox35/lib/python3.5/site-packages/numpy/core/numeric.py", line 1452, in rollaxis
    raise ValueError(msg % ('start', start, n + 1))
ValueError: rollaxis: start (4) must be >=0 and < 4
```
</details>

**Comment by perrygeo** [comment]
Also seeing the same bug on an existing 4-band test fixture

```
$ rio alpha tests/fixtures/ca_chilliwack/13-1326-2805-test-2015-2012_30cm_592_5450.tif /tmp/foo.tif
```

There's a couple ways to approach this:

#### As a bug in `alpha_mask.mask_exact`

We are rolling the axis to the depth (number of bands) when we should be using the number of *dimensions* which is almost always three. The fact that most inputs happened to have 3 bands was a coincidence that hid this bug. https://github.com/mapbox/rio-alpha/blob/master/rio_alpha/alpha_mask.py#L20-L21

#### Why `np.rollaxis`?

If we need to transpose the array to band-last/image axis order, we should use `numpy.transpose` which is roughly 3x faster and easier to read

```
np.transpose(img, [1, 2, 0])
```

#### Alpha band should take precedent

The bigger question is why are we even doing ndv masking calculations at all if the dataset has an alpha band? Per the conversation at https://github.com/mapbox/rio-alpha/issues/9#issuecomment-247447692, **we should rely on rasterio's heuristics to generate the nodata mask**. IOW, the usage of the `mask_exact` function could be replaced entirely with Rasterio's `.dataset_mask()` method.

**Comment by perrygeo** [comment]
Another related bug, if we fix mask_exact, `rio alpha` assumes that it can stack the mask on the bottom of the existing array. IOW, If we start with a 4 band array, we get 5 bands which can't be written by rasterio.
